// Dictionary of 100 most common Portuguese verbs
const dictionary = [
    { pt: "abrir", en: "to open" },
    { pt: "acabar", en: "to finish, to end" },
    { pt: "achar", en: "to think, to find" },
    { pt: "acontecer", en: "to happen" },
    { pt: "acordar", en: "to wake up" },
    { pt: "ajudar", en: "to help" },
    { pt: "andar", en: "to walk, to ride" },
    { pt: "aparecer", en: "to appear, to show up" },
    { pt: "aprender", en: "to learn" },
    { pt: "arrumar", en: "to arrange, to tidy up, to get" },
    { pt: "assistir", en: "to watch" },
    { pt: "beber", en: "to drink" },
    { pt: "botar", en: "to put, to place" },
    { pt: "chamar", en: "to call, to call out" },
    { pt: "chegar", en: "to arrive" },
    { pt: "colocar", en: "to put" },
    { pt: "começar", en: "to start, to begin" },
    { pt: "comer", en: "to eat" },
    { pt: "comprar", en: "to buy" },
    { pt: "conhecer", en: "to meet, to know" },
    { pt: "conseguir", en: "to get, to manage" },
    { pt: "contar", en: "to count, to tell" },
    { pt: "conversar", en: "to talk" },
    { pt: "cozinhar", en: "to cook" },
    { pt: "dar", en: "to give" },
    { pt: "deixar", en: "to leave, to allow" },
    { pt: "descobrir", en: "to discover, to find out" },
    { pt: "descer", en: "to go down, to descend" },
    { pt: "dever", en: "to owe, must" },
    { pt: "dizer", en: "to say" },
    { pt: "dormir", en: "to sleep" },
    { pt: "encontrar", en: "to find" },
    { pt: "entender", en: "to understand" },
    { pt: "entrar", en: "to enter" },
    { pt: "entregar", en: "to deliver" },
    { pt: "escrever", en: "to write" },
    { pt: "escutar", en: "to listen" },
    { pt: "esperar", en: "to wait, to hope" },
    { pt: "esquecer", en: "to forget" },
    { pt: "estar", en: "to be" },
    { pt: "existir", en: "to exist" },
    { pt: "explicar", en: "to explain" },
    { pt: "falar", en: "to speak" },
    { pt: "faltar", en: "to lack, to miss" },
    { pt: "fechar", en: "to close" },
    { pt: "ficar", en: "to stay, to become" },
    { pt: "funcionar", en: "to work, to function" },
    { pt: "ganhar", en: "to win, to earn" },
    { pt: "gostar", en: "to like" },
    { pt: "haver", en: "there to be" },
    { pt: "ir", en: "to go" },
    { pt: "jogar", en: "to play, to throw" },
    { pt: "lembrar", en: "to remember" },
    { pt: "levantar", en: "to get up" },
    { pt: "levar", en: "to take, to carry" },
    { pt: "ligar", en: "to call, to turn on" },
    { pt: "limpar", en: "to clean" },
    { pt: "mandar", en: "to send, to order" },
    { pt: "morar", en: "to reside, to live" },
    { pt: "mostrar", en: "to show" },
    { pt: "mudar", en: "to change" },
    { pt: "olhar", en: "to look" },
    { pt: "ouvir", en: "to hear" },
    { pt: "pagar", en: "to pay" },
    { pt: "parar", en: "to stop" },
    { pt: "parecer", en: "to seem" },
    { pt: "passar", en: "to pass, to stop by" },
    { pt: "pedir", en: "to ask" },
    { pt: "pegar", en: "to take" },
    { pt: "pensar", en: "to think" },
    { pt: "perder", en: "to lose" },
    { pt: "perguntar", en: "to ask" },
    { pt: "poder", en: "can, may" },
    { pt: "pôr", en: "to put" },
    { pt: "precisar", en: "to need" },
    { pt: "preocupar", en: "to worry" },
    { pt: "procurar", en: "to search for" },
    { pt: "querer", en: "to want" },
    { pt: "receber", en: "to receive" },
    { pt: "responder", en: "to answer" },
    { pt: "saber", en: "to know" },
    { pt: "sair", en: "to leave" },
    { pt: "sentar", en: "to sit" },
    { pt: "sentir", en: "to feel" },
    { pt: "ser", en: "to be" },
    { pt: "subir", en: "to go up, to climb" },
    { pt: "tentar", en: "to try, to test" },
    { pt: "ter", en: "to have" },
    { pt: "terminar", en: "to finish" },
    { pt: "tirar", en: "to remove, to take off" },
    { pt: "tocar", en: "to ring, to play, to touch" },
    { pt: "tomar", en: "to take, to drink" },
    { pt: "trabalhar", en: "to work" },
    { pt: "trazer", en: "to bring" },
    { pt: "trocar", en: "to change, to exchange" },
    { pt: "usar", en: "to use" },
    { pt: "ver", en: "to see" },
    { pt: "vir", en: "to come" },
    { pt: "viver", en: "to live" },
    { pt: "voltar", en: "to come back" }
];
