// Dictionary of 100 most common Portuguese verbs
const dictionary = [
    { portuguese: "abrir", english: "to open" },
    { portuguese: "acabar", english: "to finish, to end" },
    { portuguese: "achar", english: "to think, to find" },
    { portuguese: "acontecer", english: "to happen" },
    { portuguese: "acordar", english: "to wake up" },
    { portuguese: "ajudar", english: "to help" },
    { portuguese: "andar", english: "to walk, to ride" },
    { portuguese: "aparecer", english: "to appear, to show up" },
    { portuguese: "aprender", english: "to learn" },
    { portuguese: "arrumar", english: "to arrange, to tidy up, to get" },
    { portuguese: "assistir", english: "to watch" },
    { portuguese: "beber", english: "to drink" },
    { portuguese: "botar", english: "to put, to place" },
    { portuguese: "chamar", english: "to call, to call out" },
    { portuguese: "chegar", english: "to arrive" },
    { portuguese: "colocar", english: "to put" },
    { portuguese: "começar", english: "to start, to begin" },
    { portuguese: "comer", english: "to eat" },
    { portuguese: "comprar", english: "to buy" },
    { portuguese: "conhecer", english: "to meet, to know" },
    { portuguese: "conseguir", english: "to get, to manage" },
    { portuguese: "contar", english: "to count, to tell" },
    { portuguese: "conversar", english: "to talk" },
    { portuguese: "cozinhar", english: "to cook" },
    { portuguese: "dar", english: "to give" },
    { portuguese: "deixar", english: "to leave, to allow" },
    { portuguese: "descobrir", english: "to discover, to find out" },
    { portuguese: "descer", english: "to go down, to descend" },
    { portuguese: "dever", english: "to owe, must" },
    { portuguese: "dizer", english: "to say" },
    { portuguese: "dormir", english: "to sleep" },
    { portuguese: "encontrar", english: "to find" },
    { portuguese: "entender", english: "to understand" },
    { portuguese: "entrar", english: "to enter" },
    { portuguese: "entregar", english: "to deliver" },
    { portuguese: "escrever", english: "to write" },
    { portuguese: "escutar", english: "to listen" },
    { portuguese: "esperar", english: "to wait, to hope" },
    { portuguese: "esquecer", english: "to forget" },
    { portuguese: "estar", english: "to be" },
    { portuguese: "existir", english: "to exist" },
    { portuguese: "explicar", english: "to explain" },
    { portuguese: "falar", english: "to speak" },
    { portuguese: "faltar", english: "to lack, to miss" },
    { portuguese: "fechar", english: "to close" },
    { portuguese: "ficar", english: "to stay, to become" },
    { portuguese: "funcionar", english: "to work, to function" },
    { portuguese: "ganhar", english: "to win, to earn" },
    { portuguese: "gostar", english: "to like" },
    { portuguese: "haver", english: "there to be" },
    { portuguese: "ir", english: "to go" },
    { portuguese: "jogar", english: "to play, to throw" },
    { portuguese: "lembrar", english: "to remember" },
    { portuguese: "levantar", english: "to get up" },
    { portuguese: "levar", english: "to take, to carry" },
    { portuguese: "ligar", english: "to call, to turn on" },
    { portuguese: "limpar", english: "to clean" },
    { portuguese: "mandar", english: "to send, to order" },
    { portuguese: "morar", english: "to reside, to live" },
    { portuguese: "mostrar", english: "to show" },
    { portuguese: "mudar", english: "to change" },
    { portuguese: "olhar", english: "to look" },
    { portuguese: "ouvir", english: "to hear" },
    { portuguese: "pagar", english: "to pay" },
    { portuguese: "parar", english: "to stop" },
    { portuguese: "parecer", english: "to seem" },
    { portuguese: "passar", english: "to pass, to stop by" },
    { portuguese: "pedir", english: "to ask" },
    { portuguese: "pegar", english: "to take" },
    { portuguese: "pensar", english: "to think" },
    { portuguese: "perder", english: "to lose" },
    { portuguese: "perguntar", english: "to ask" },
    { portuguese: "poder", english: "can, may" },
    { portuguese: "pôr", english: "to put" },
    { portuguese: "precisar", english: "to need" },
    { portuguese: "preocupar", english: "to worry" },
    { portuguese: "procurar", english: "to search for" },
    { portuguese: "querer", english: "to want" },
    { portuguese: "receber", english: "to receive" },
    { portuguese: "responder", english: "to answer" },
    { portuguese: "saber", english: "to know" },
    { portuguese: "sair", english: "to leave" },
    { portuguese: "sentar", english: "to sit" },
    { portuguese: "sentir", english: "to feel" },
    { portuguese: "ser", english: "to be" },
    { portuguese: "subir", english: "to go up, to climb" },
    { portuguese: "tentar", english: "to try, to test" },
    { portuguese: "ter", english: "to have" },
    { portuguese: "terminar", english: "to finish" },
    { portuguese: "tirar", english: "to remove, to take off" },
    { portuguese: "tocar", english: "to ring, to play, to touch" },
    { portuguese: "tomar", english: "to take, to drink" },
    { portuguese: "trabalhar", english: "to work" },
    { portuguese: "trazer", english: "to bring" },
    { portuguese: "trocar", english: "to change, to exchange" },
    { portuguese: "usar", english: "to use" },
    { portuguese: "ver", english: "to see" },
    { portuguese: "vir", english: "to come" },
    { portuguese: "viver", english: "to live" },
    { portuguese: "voltar", english: "to come back" }
];
